### ISSUE TITLE
我这个是python版本问题吗？

### ISSUE THREAD

**Issue by GrowingHacker** [m790641512/Wechat-bombing-script#3]
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\1\Wechat-bombing-script\微信轰炸.py", line 54, in <module>
    itchat.auto_login(hotReload=True)
  File "C:\Users\HUAWEI\PycharmProjects\lib\site-packages\itchat\components\register.py", line 31, in auto_login
    self.login(enableCmdQR=enableCmdQR, picDir=picDir, qrCallback=qrCallback,
  File "C:\Users\HUAWEI\PycharmProjects\lib\site-packages\itchat\components\login.py", line 53, in login
    status = self.check_login()
  File "C:\Users\HUAWEI\PycharmProjects\lib\site-packages\itchat\components\login.py", line 137, in check_login
    if process_login_info(self, r.text):
  File "C:\Users\HUAWEI\PycharmProjects\lib\site-packages\itchat\components\login.py", line 172, in process_login_info
    for node in xml.dom.minidom.parseString(r.text).documentElement.childNodes:
  File "C:\Users\HUAWEI\PycharmProjects\lib\xml\dom\minidom.py", line 1998, in parseString
    return expatbuilder.parseString(string)
  File "C:\Users\HUAWEI\PycharmProjects\lib\xml\dom\expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "C:\Users\HUAWEI\PycharmProjects\lib\xml\dom\expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: mismatched tag: line 63, column 4

**Comment by MBarcak** [comment]
微信官方对网页版微信进行了一些限制，导致第三方库例如itchat的登陆功能受到了影响。如果您的微信号无法登陆网页版微信的话这个脚本是没法使用的。
